[tool.poetry]
name = "converter"
version = "0.1.0"
description = ""
authors = ["Dmitriy <b8ea5t@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
moviepy = "^1.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
